name: Checks

on:
  pull_request:
    branches: [main]

jobs:
  test-lint:
    name: Test and Lint
    uses: Cloud-Project-AWS-/.github/workflows/test-and-lint.yml
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
