---
  name: Checks
  
  on:
    pull_request:
      branches: [main]
  
  jobs:
    test-lint:
      name: Test and Lint
      uses: ./.github/workflows/test-and-lint.yml  # Ensure this file exists
      secrets:
        DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  